/*
 * base.h
 *
 *  Created on: Apr 25, 2026
 *      Author: Hp
 */

#ifndef BASE_H_
#define BASE_H_

#define PERIPHERAL_BASE				(0x40000000)

#define APB1_PERIPHERAL_OFFSET  	(0x0000)
#define APB1_PERIPHERAL    			(PERIPHERAL_BASE + APB1_PERIPHERAL_OFFSET)

#define APB2_PERIPHERAL_OFFSET  	(0x00010000)
#define APB2_PERIPHERAL    			(PERIPHERAL_BASE + APB2_PERIPHERAL_OFFSET)

#define AHB_PERIPHERAL_OFFSET   	(0x00020000)
#define AHB_PERIPHERAL 				(PERIPHERAL_BASE + AHB_PERIPHERAL_OFFSET)

#define I2C_PERIPHERAL_OFFSET 		(0x00005400)
#define I2C_PERIPHERAL				(APB1_PERIPHERAL + I2C_PERIPHERAL_OFFSET)

#define GPIOA_PERIPHERAL_OFFSET 	(0x00000800)
#define GPIOA_PERIPHERAL			(APB2_PERIPHERAL + GPIOA_PERIPHERAL_OFFSET)

#define GPIOB_PERIPHERAL_OFFSET 	(0x00000C00)
#define GPIOB_PERIPHERAL			(APB2_PERIPHERAL + GPIOB_PERIPHERAL_OFFSET)

#define RCC_PERIPHERAL_OFFSET		(0x00001000)
#define RCC_PERIPHERAL 				(AHB_PERIPHERAL + RCC_PERIPHERAL_OFFSET)

//rcc register

#define RCC_APB2ENR_OFFSET			(0x18)
#define RCC_APB2ENR					(*(volatile unsigned int *)(RCC_PERIPHERAL + RCC_APB2ENR_OFFSET))

#define RCC_APB1ENR_OFFSET			(0x1C)
#define RCC_APB1ENR					(*(volatile unsigned int *)(RCC_PERIPHERAL + RCC_APB1ENR_OFFSET))

#endif /* BASE_H_ */
